# Generated by Django 5.1.6 on 2025-03-04 16:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoTuner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("actions_taken", models.JSONField()),
                ("success", models.BooleanField()),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_tuners",
                        to="core.optimizationprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_tuners",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auto_tuners",
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="auto_tuners_timesta_71bb42_idx"
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="auto_tuners_user_id_febc03_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AutoTuningResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("metrics_before", models.JSONField()),
                ("metrics_after", models.JSONField()),
                ("actions_taken", models.JSONField()),
                ("success", models.BooleanField()),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_tuning_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auto_tuning_results",
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="auto_tuning_timesta_14e826_idx"
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="auto_tuning_user_id_59af75_idx",
                    ),
                ],
            },
        ),
    ]
